# Generated by Django 4.2.2 on 2023-06-25 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('position', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('employment_date', models.DateField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Level 2: Directors',
                'ordering': ('position', 'surname', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DistrictManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('position', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('employment_date', models.DateField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Level 4: District managers',
                'ordering': ('position', 'surname', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('position', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('employment_date', models.DateField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Level 6: Specialists',
                'ordering': ('position', 'surname', 'name'),
            },
        ),
        migrations.CreateModel(
            name='TopManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('position', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('employment_date', models.DateField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Level 1: Top managers',
                'ordering': ('position', 'surname', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('position', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('employment_date', models.DateField(max_length=10)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tree_structure.specialist')),
            ],
            options={
                'verbose_name_plural': 'Level 7: Trainee',
                'ordering': ('position', 'surname', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Teamlead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('position', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('employment_date', models.DateField(max_length=10)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tree_structure.districtmanager')),
            ],
            options={
                'verbose_name_plural': 'Level 5: Teamleads',
                'ordering': ('position', 'surname', 'name'),
            },
        ),
        migrations.AddField(
            model_name='specialist',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tree_structure.teamlead'),
        ),
        migrations.CreateModel(
            name='RegionalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('position', models.CharField(db_index=True, max_length=50)),
                ('surname', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(db_index=True, max_length=50)),
                ('employment_date', models.DateField(max_length=10)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tree_structure.director')),
            ],
            options={
                'verbose_name_plural': 'Level 3: Regional managers',
                'ordering': ('position', 'surname', 'name'),
            },
        ),
        migrations.AddField(
            model_name='districtmanager',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tree_structure.regionalmanager'),
        ),
        migrations.AddField(
            model_name='director',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tree_structure.topmanager'),
        ),
    ]
